CREATE TABLE [dbo].[Customer]
(
	[Id] BIGINT NOT NULL CONSTRAINT PK_Customer PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL,
	[Email] VARCHAR(255) NOT NULL,
	[Phone] VARCHAR(20) NULL,
	[Address] VARCHAR(255) NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
)
