CREATE TABLE [dbo].[Product]
(
	[Id] BIGINT NOT NULL CONSTRAINT PK_Product PRIMARY KEY,
	[Name] VARCHAR(255) NOT NULL,
	[Description] VARCHAR(255) NOT NULL,
	[Price] DECIMAL(18, 2) NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
)
